// ============================================================
//  ⚠️  AUTO-GENERATED by updater.py — do not edit by hand.
//     Edit the info.js inside each project folder instead,
//     then re-run:  python3 updater.py
// ============================================================

var PROJECTS = [

  { name: "cyber_procedural",
    desc: "Selection of Procedural web images with cyber/chip influences.",
    created: "2026-01-13",
    type: "website",
    tags: ["procedural", "website"] },

  { name: "obsidian_conspiracy_board_graph",
    desc: "An Obisidian plugin to display documents on a conspiracy board",
    created: "2025-08-11",
    type: "obsidian plugin",
    tags: ["obsidian"] },

  { name: "obsidian_corkboard_view",
    desc: "An Obisidian plugin to display documents on a corkboard.",
    created: "2025-07-11",
    type: "obsidian plugin",
    tags: ["obsidian"] },

  { name: "obsidian_radar_chart",
    desc: "An Obisidian plugin to create custom radar charts in Obsidian documents.",
    created: "2025-06-11",
    type: "obsidian plugin",
    tags: ["obsidian"] },

  { name: "recommendations",
    desc: "Curated recommendations of my favourite things.",
    created: "2025-25-12",
    type: "website",
    tags: ["web", "react"] }
];
