#!/usr/bin/env python3
"""
updater.py — rebuilds projects.js from individual project info.js files.

Run from the root of the website:
    python3 updater.py

Each project folder under ./projects/ should contain an info.js like:

    info = {
      name:    "My Project",
      desc:    "What this project does.",
      created: "2024-03-15",
      type:    "website",
      tags:    ["web", "react"],
    };

Or equivalently as a bare object:

    ({
      desc:    "What this project does.",
      created: "2024-03-15",
      type:    "website",
      tags:    ["web", "react"],
    })

The folder name becomes the project's `name` automatically.
`type` is optional and defaults to "website".
`created` is optional.
"""

import os
import re
import json
import sys
from pathlib import Path

# ── Config ────────────────────────────────────────────────────
PROJECTS_DIR = Path(__file__).parent / "projects"
OUTPUT_FILE  = Path(__file__).parent / "projects.js"
# ──────────────────────────────────────────────────────────────


def parse_info_js(path: Path) -> dict:
    """
    Parse an info.js file into a Python dict.
    Accepts JS object literals (not strict JSON) by:
      - stripping outer ( ) wrappers
      - removing trailing commas before } or ]
      - converting single-quoted strings to double-quoted
      - stripping JS-style // comments
    """
    text = path.read_text(encoding="utf-8")

    # Remove // line comments
    text = re.sub(r"//[^\n]*", "", text)
    text = text.strip()

    # Strip variable assignment: info = { or var/let/const info = {
    text = re.sub(r"^(var\s+|let\s+|const\s+)?\w+\s*=\s*", "", text).strip()

    # Strip trailing semicolon
    if text.endswith(";"):
        text = text[:-1].strip()

    # Strip outer parens if present: ({ ... })
    if text.startswith("(") and text.endswith(")"):
        text = text[1:-1].strip()

    # Trailing commas before } or ] — not valid JSON
    text = re.sub(r",\s*([}\]])", r"\1", text)

    # Tokenise into string / non-string segments so we never mangle string values.
    # Only non-string segments get key-quoting and single→double quote conversion.
    tokens = re.split(r'("(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\')', text)
    result = []
    for i, token in enumerate(tokens):
        if i % 2 == 1:
            # Inside a quoted string — convert single-quoted to double-quoted only
            if token.startswith("'"):
                token = '"' + token[1:-1] + '"'
            result.append(token)
        else:
            # Outside strings — safe to quote unquoted keys
            token = re.sub(r"'([^']*)'", r'"\1"', token)
            token = re.sub(r"(?<=[{,\s])(\w+)\s*:", r'"\1":', token)
            result.append(token)

    text = "".join(result)

    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        raise ValueError(f"Could not parse {path}: {e}\n\nProcessed text:\n{text}")
def format_project(data: dict, name: str) -> str:
    """Render a single project entry in the projects.js style."""
    tags = data.get("tags", [])
    tags_str = "[" + ", ".join(f'"{t}"' for t in tags) + "]"

    fields = [f'name: "{name}"']

    if "desc" in data:
        fields.append(f'desc: "{data["desc"]}"')
    if "created" in data:
        fields.append(f'created: "{data["created"]}"')
    if "type" in data:
        fields.append(f'type: "{data["type"]}"')

    fields.append(f"tags: {tags_str}")

    # Align values: first field on same line as {, rest indented
    first = fields[0]
    rest  = (",\n" + " " * 4).join(fields[1:])
    return f"  {{ {first},\n    {rest} }}"


def main():
    if not PROJECTS_DIR.exists():
        print(f"✗  projects directory not found: {PROJECTS_DIR}", file=sys.stderr)
        sys.exit(1)

    entries    = []
    skipped    = []
    errored    = []

    # Sort folders alphabetically for stable output
    folders = sorted(
        p for p in PROJECTS_DIR.iterdir()
        if p.is_dir() and not p.name.startswith(".")
    )

    for folder in folders:
        info_path = folder / "info.js"

        if not info_path.exists():
            skipped.append(folder.name)
            continue

        try:
            data = parse_info_js(info_path)
            entries.append(format_project(data, folder.name))
            print(f"  ✓  {folder.name}")
        except ValueError as e:
            errored.append(folder.name)
            print(f"  ✗  {folder.name}: {e}", file=sys.stderr)

    # ── Write projects.js ──
    header = """\
// ============================================================
//  ⚠️  AUTO-GENERATED by updater.py — do not edit by hand.
//     Edit the info.js inside each project folder instead,
//     then re-run:  python3 updater.py
// ============================================================

var PROJECTS = [

"""
    footer = "\n];\n"
    body   = ",\n\n".join(entries)

    OUTPUT_FILE.write_text(header + body + footer, encoding="utf-8")

    # ── Summary ──
    print()
    print(f"✓  Wrote {len(entries)} project(s) to {OUTPUT_FILE.name}")
    if skipped:
        print(f"   Skipped (no info.js): {', '.join(skipped)}")
    if errored:
        print(f"   Errored: {', '.join(errored)}")
        sys.exit(1)


if __name__ == "__main__":
    main()